### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by brettinternet** [angelnu/pod-gateway#5]
# Details

**Describe the solution you'd like:**
Has the community adopted a new helm chart to use with this container?

**Anything else you would like to add:**
As context for others, the old helm charts have been deprecated: https://github.com/k8s-at-home/charts/tree/master/charts/stable/pod-gateway.

**Comment by angelnu** [comment]
Not yet - you need to manually change the image in the existing k8s-at-home chart for now.

I will set up my own Helm charts repo next following the example of the other members - maybe this weekend if weather is not too good :-)

**Comment by angelnu** [comment]
The chart is available: https://github.com/angelnu/helm-charts/tree/main/charts/apps/pod-gateway

You can see how I use it at my k8s cluster: https://github.com/angelnu/k8s-gitops/blob/main/core/vpn-gateway/release.yaml

The largest change is that `gluetun` must be used as the common library removed support for openvpn or wireguard (as gluetun supports both).

**Comment by brettinternet** [comment]
Awesome! Thank you!
